<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <!--<Compile Include="StringExtensions.fs" />
    <Compile Include="Transaction.fs" />
    <Compile Include="Investment.fs" />
    <Compile Include="PortfolioInitializer.fs" />
    <Compile Include="ProcessInvestmentsPartOfVanguardDataFile.fs" />-->   
    <Compile Include="ToCleanDecimal.fs" />   
    <None Include="MultiClassQueueingNetwork.fsx" />   
    <Compile Include="ValidationResult.fs" />   
    <Compile Include="Validator.fs" />   
    <Compile Include="Investment.fs" />   
    <Compile Include="Transaction.fs" />   
    <Compile Include="ProcessInvestmentPartOfVanguardDataFile.fs" />   
    <Compile Include="ProcessTransactionPartOfVanguardDataFile.fs" />   
    <Compile Include="PortfolioInitializer.fs" />   
    <Compile Include="ParseVanguardDataFile.fs" />   
    <Compile Include="HtmlReportLayout.fs" />   
    <Compile Include="HtmlTableBuilder.fs" />   
    <Compile Include="GenerateGenericInvestmentReport.fs" />   
    <Compile Include="GenerateGenericTransactionReport.fs" />   
    <Compile Include="GenerateInvestmentReport.fs" />   
    <Compile Include="GenerateDistributionsReport.fs" />   
    <Compile Include="GenerateListOfBuyTransactions.fs" />   
    <Compile Include="GenerateListOfCashReport.fs" />   
    <Compile Include="GenerateListOfCorpActions.fs" />   
    <Compile Include="GenerateListOfDividendsReport.fs" />   
    <Compile Include="GenerateListOfFees.fs" />   
    <Compile Include="GenerateListOfInterestPayments.fs" />   
    <Compile Include="GenerateListOfSellTransactions.fs" />   
    <Compile Include="GenerateListOfTBillsReport.fs" />   
    <Compile Include="GenerateDividendTransactionReport.fs" />   
    <Compile Include="Library.fs" />
  </ItemGroup>

</Project>
