<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RunAnalyzersDuringBuild>True</RunAnalyzersDuringBuild>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>  
    <None Include="MultiClassQueueingNetwork.fsx" />  
    <Compile Include="StringExtensions.fs" />   
    <Compile Include="HtmlReportComponents.fs" />   
    <Compile Include="Validatiomn.fs" />   
    <Compile Include="VanguardModels.fs" />   
    <Compile Include="VanguardDataIngestion.fs" />   
    <Compile Include="PortfolioInitializer.fs" />   
    <Compile Include="PortfolioReports.fs" />   
    <Compile Include="ParseVanguardDataFile.fs" />
  </ItemGroup>

</Project>
