<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>  
    <Compile Include="StringExtensions.fs" />   
    <None Include="MultiClassQueueingNetwork.fsx" />   
    <Compile Include="Validatiomn.fs" />   
    <Compile Include="VanguardModels.fs" />   
    <Compile Include="VanguardDataIngestion.fs" />   
    <Compile Include="PortfolioInitializer.fs" />   
    <Compile Include="HtmlReportComponents.fs" />   
    <Compile Include="PortfolioReports,fs.fs" />   
    <Compile Include="GenerateGenericInvestmentReport.fs" />   
    <Compile Include="GenerateGenericTransactionReport.fs" />   
    <Compile Include="GenerateInvestmentReport.fs" />   
    <Compile Include="GenerateDistributionsReport.fs" />   
    <Compile Include="GenerateListOfBuyTransactions.fs" />   
    <Compile Include="GenerateListOfCashReport.fs" />   
    <Compile Include="GenerateListOfCorpActions.fs" />   
    <Compile Include="GenerateListOfDividendsReport.fs" />   
    <Compile Include="GenerateListOfFees.fs" />   
    <Compile Include="GenerateListOfInterestPayments.fs" />   
    <Compile Include="GenerateListOfSellTransactions.fs" />   
    <Compile Include="GenerateListOfTBillsReport.fs" />   
    <Compile Include="GenerateDividendTransactionsReport.fs" />   
    <Compile Include="ParseVanguardDataFile.fs" />   
    <Compile Include="Library.fs" />
  </ItemGroup>

</Project>
